spring:
  application:
    name: gateway
  data:
    redis:
      database: 1
      host: '112.124.24.102'
      port: 6379
      password: '050416'
  # 开启虚拟线程
  threads:
    virtual:
      enabled: true
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/user/**
security:
  ignore:
    urls:
      - /api/user/login
      - /api/user/register
      - /api/user/captcha
      - /api/user/ping

management:
  endpoints:
    web:
       exposure:
         include: "*"
server:
  port: 8080