spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  data:
    redis:
      database: 1
      host: '112.124.24.102'
      port: 6379
      password: '050416'
  # 开启虚拟线程
  threads:
    virtual:
      enabled: true

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: gateway
        prefer-ip-address: true
        ip-address: 127.0.0.1
        health-check-path: /actuator/health
        health-check-interval: 10s
        register: true

    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: user
              uri: lb://user
              predicates:
                - Path=/api/user/**
            - id: product
              uri: lb://product
              predicates:
                - Path=/api/product/**
            - id: admin
              uri: lb://admin
              predicates:
                - Path=/api/admin/**
security:
  ignore:
    urls:
      - /api/user/login
      - /api/user/register
      - /api/user/captcha
      - /api/admin/login

management:
  endpoints:
    web:
       exposure:
         include: "health"
server:
  port: 8080