server:
  port: 80

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**

        - id: travel-product
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**

        - id: travel-order
          uri: http://localhost:8083
          predicates:
            - Path=/api/orders/**



