spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: product
          uri: lb://product
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
            '[/**]':
                allowedOrigins: "*"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
server:
  port: 80
travel:
  auth:
    white-paths:
      - /api/user/login
      - /api/user/register



