package com.qtfycg.product.entity;

import lombok.Data;

import java.math.BigDecimal;

@Data
public class product {
    private Long id;
    private String title;
    private String destination;
    private BigDecimal price;
    private Integer days;
    private String description;
    private Integer type;
    private Integer status;



    // Constructors, getters, and setters can be generated by Lombok
}
