spring:
  application:
    name: travel-api
    # 数据库配置
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://112.12.102.24:3306/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2
