server:
  port: 8080
jwt:
  secret: '159357qaz'
  expiration: '3600000'

spring:
  # 主数据库配置
  config:
    import: optional:classpath:application-datasource.yml
  # user数据库配置
  datasource:
    url: jdbc:mysql://112.124.24.102:3306/travel?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: '050406'
  application:
    name: user
